name: test apksigner

on:
  push:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: dll
      run: | 
        wget https://dl.google.com/android/repository/build-tools_r31-linux.zip
        unzip *.zip
        
    - name: apksigner
      run: android-12/apksigner
        
    - name: lsd
      run: ls -R
