name: test apksigner

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: dll
      run: | 
        mkdir dt
        cd dt
        wget https://dl.google.com/android/repository/build-tools_r31-linux.zip
        unzip *.zip .
        rm *.zip
      
    - name: lsd
      run: ls -R
