# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: dllf

on:
  workflow_dispatch:
    inputs:
      url: 
        type: string 
        required: true
        description: url to download
      part_size:
        type: string
        required: false
        description: 'parts size (mb) (min:10mb)'
        default: '100'
      filename:
        type: string
        required: false
        default: ''
      reltag:
        type: string
        description: release tag
        required: false
        default: ''

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: chk Ip
      run: curl ipecho.net/plain; echo
      continue-on-error: true
    
    - name: set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
      
    - name: build Splitter
      run: javac Splitter.java
      
    - name: download file
      run: | 
        mkdir bin
        cd bin
        wget ${{ inputs.url }}

    - name: lsd
      run: ls -R -lh

    
        
    - name: upload raw
      uses: actions/upload-artifact@v4.3.3
      with:
        name: file.zip
        path: bin
    
    - name: splitt
      run: java Splitter bin "${{inputs.part_size}}"

    - name: Upload to Release Action
      uses: svenstaro/upload-release-action@2.11.3
      with:
        asset_name: splits
        file: bin/*
        repo_token: ${{ secrets.GITHUB_TOKEN }}
      
    - name: ls dirp
      run: ls -R -lh
      
