# This is a basic workflow that is manually triggered

name: ytdll

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts. 
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'youtube url'
        # Default value if no value is explicitly provided
        #default: ''
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: echo "Hello ${{ inputs.name }}"

    - name: wget ffmpeg
      run: |
        mkdir ffm
        cd ffm
        wget https://ffmpeg.org/releases/ffmpeg-7.0.1.tar.gz
        tar -xz *.tar.gz

    - name: wget ytdlp
      run: |
        wget https://github.com/ytdl-org/ytdl-nightly/releases/download/2024.06.12/youtube-dl
        chmod 777 ./youtube-dl

    - name: get file
      run: |
        mkdir out1
        cd out1
        ../youtube-dl ${{inputs.name}}
      
    - name: lsd
      run: ls -lhR

    - name: upload file
      uses: actions/upload-artifact@v4.3.3
      with:
        name: file1234.zip
        path: out1
        
        
    
      
